### PR TITLE
Remove `em()` Sass mixin

### PR DESCRIPTION
**Pull request by alex-ju**
## What
Remove `em()` Sass mixin

## Why
This was deprecated for a while now and it's no longer used in GOV.UK applications.
Fixes https://github.com/alphagov/govuk_publishing_components/issues/2035

## Visual Changes
No visual changes

### CODE REVIEW

**Review by andysellick — APPROVED** [review]
Looks good. If this isn't in use anymore does this still count as a breaking change?

(also need to update the changelog)

**Comment by alex-ju** [comment]
> Looks good. If this isn't in use anymore does this still count as a breaking change?

It is technically a breaking change and I haven't looked anywhere outside our core frontend apps so I thought we could bundle it with [others in the pipeline](https://github.com/alphagov/govuk_publishing_components/milestone/5).

**Comment by andysellick** [comment]
> It is technically a breaking change and I haven't looked anywhere outside our core frontend apps so I thought we could bundle it with [others in the pipeline](https://github.com/alphagov/govuk_publishing_components/milestone/5).

Good shout. I've just noticed it's also a breaking change because static explicitly imports this file: https://github.com/alphagov/static/blob/main/app/assets/stylesheets/header-footer-only.scss#L6

**Comment by alex-ju** [comment]
> Looks good. If this isn't in use anymore does this still count as a breaking change?
> 
> (also need to update the changelog)

It oddly imports it without using it.. 🤷 
Will remove it from `static` beforehand to make dependabot happy.

**Pull request merged**
