### PR TITLE
bump to version 17.14.0

### PR DESCRIPTION
**Pull request by DilwoarH**
Includes:
* Change paragraph to div for descriptions to support govspeak (PR #985)
* Update cookie banner component to hide if cross-origin message has `hideCookieBanner` set to `true` (PR #988)

### CODE REVIEW

**Comment by vanitabarrett** [comment]
I would say this is probably a patch release, so 17.13.1

**Comment by DilwoarH** [comment]
@vanitabarrett good point, updated

**Comment by alex-ju** [comment]
Now that #988 is in, could we rebase and make it 17.14.0 again? 😁

**Comment by DilwoarH** [comment]
@alex-ju updated

**Pull request merged**
