### PR TITLE
Make the component wrapper more robust

### PR DESCRIPTION
**Pull request by andysellick**
## What
Improve the component wrapper helper in the following ways.

- let it recognise if blank or nil values are passed for certain things. Previously it was possible to pass `nil` as an ID attribute, at which point the wrapper would error because `nil` is not a valid HTML ID, rather than simply ignoring it
- improve the error messages to include the thing that is causing the error, in order to make troubleshooting issues easier

## Why
`Frontend` had a bit of code where `nil` was being [passed to a component as an ID](https://github.com/alphagov/frontend/commit/44a16abd2888cb0dddbb4a2d01f5a75477bbb089), which was causing the build to fail. This change should prevent similar errors in the future.

## Visual Changes
None.

### CODE REVIEW

**Review by jon-kirwan — APPROVED** [review]
All seems good and works fine for me (I've tested the same `frontend` page).

The only comment I have, which would be a separate issue, is whether we should add another method to check for valid or accepted data attributes (for things like "track-" or "module") but an invalid data attribute is going to to have less impact than an invalid class or ARIA attribute so maybe not necessary.

**Comment by andysellick** [comment]
> The only comment I have, which would be a separate issue, is whether we should add another method to check for valid or accepted data attributes (for things like "track-" or "module") but an invalid data attribute is going to to have less impact than an invalid class or ARIA attribute so maybe not necessary.

Thanks @jon-kirwan. Very interesting question! I'd omitted checking this so far because data attributes can be anything, so long as they start with `data-`, but thinking about it now I realise you could check for some invalid input at least (e.g. with spaces in) so will have a think.

**Comment by andysellick** [comment]
@jon-kirwan I've had a go at validating data attributes - have added an extra commit if you'd like to take a look when you have time, thanks.

**Comment by jon-kirwan** [comment]
Nice one! All looks good to me. I've tested from the component guide and an application (`feedback`) entering various invalid data attribute combinations (e.g. `moDule`, `mo dule`) which are correctly raise an ArgumentError with a warning message: `Data attributes (moDule) cannot contain capitals, spaces or colons, or start with 'xml'"`

**Pull request merged**
