### PR TITLE
Switch from ruby-sass to sassc

### PR DESCRIPTION
**Pull request by kevindew**
## What

This removes this app having a dependency on ruby-sass and, more importantly, forcing this on all consumers of the gem. This then switches the sass rails dependency to be sassc-rails and also development only (as it's not something consumers of this gem necessarily need).

This then changes the configuration of sass to do compilation during the initial run of building css, rather than in Rails' secondary css_compressor stage. This resolves the [the `Error: "calc(0px)" is not a number for `max'` issue](https://github.com/alphagov/finder-frontend/issues/1124).

## Why

Ruby-sass is now end-of-life and GOV.UK still uses it heavily. For any apps to start moving away from it we need this gem to not push ruby-sass as a dependency. 

This app is also one of the few govuk tools that doesn't use https://github.com/alphagov/scss-lint-govuk so can actually use libsass.

## Visual Changes

None - I hope 🤞 

## Caveats

This offers a performance boost for the initial compilation of CSS but does carry a performance penalty for accessing CSS from a warm cache. This is a characteristic of https://github.com/alphagov/govuk-frontend/issues/1671.

I've found the warm cache times don't prove to be too dramatic (2-3 seconds) on my local machine. These would be worse using govuk-docker though (I saw around 9 seconds). I'm assuming that not many people use govuk-docker to develop on this gem as there doesn't seem to be many benefits to doing so (I'm not really sure why we have configuration for gems in govuk-docker), but if people do use that a lot then we may want to back out of it. If we do choose to back out the route forward would be adding sass as a development_dependency and changing to a dependency on sass-rails rather than reverting the whole PR.

From my recent chats with the design system we should be due to see a release in 2 to 3 weeks of govuk-frontend that vastly improves that performance issue.

## Future avenues

As part of this I looked into sprockets 4 and believe I resolved the issues that led to a [previous revert](https://github.com/alphagov/govuk_publishing_components/pull/1172) - I did however get stuck on https://github.com/rails/sprockets-rails/issues/458 so decided to park this for later.

### CODE REVIEW

**Comment by benthorner** [comment]
I had a quick try of this in Content Publisher (after `yarn install`) and got the following error.

```
Showing /home/build/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/bundler/gems/govuk_publishing_components-4a3828a5bb8b/app/views/govuk_publishing_components/components/_layout_for_admin.html.erb where line #11 raised:

couldn't find file 'axe-core/axe.js' with type 'application/javascript'
Checked in these paths: 
  /govuk/content-publisher/app/assets/config
  /govuk/content-publisher/app/assets/images
  /govuk/content-publisher/app/assets/javascripts
  /govuk/content-publisher/app/assets/stylesheets
  /home/build/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/bundler/gems/govuk_publishing_components-4a3828a5bb8b/app/assets/config
  /home/build/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/bundler/gems/govuk_publishing_components-4a3828a5bb8b/app/assets/images
  /home/build/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/bundler/gems/govuk_publishing_components-4a3828a5bb8b/app/assets/javascripts
  /home/build/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/bundler/gems/govuk_publishing_components-4a3828a5bb8b/app/assets/stylesheets
  /home/build/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/activestorage-6.0.2.2/app/assets/javascripts
  /home/build/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/actionview-6.0.2.2/lib/assets/compiled
  /home/build/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/bundler/gems/govuk_publishing_components-4a3828a5bb8b/node_modules/govuk-frontend/govuk/assets/images
  /home/build/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/bundler/gems/govuk_publishing_components-4a3828a5bb8b/node_modules/govuk-frontend/govuk/assets/fonts
  /home/build/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/bundler/gems/govuk_publishing_components-4a3828a5bb8b/node_modules/govuk-frontend
  /home/build/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/bundler/gems/govuk_publishing_components-4a3828a5bb8b/node_modules
  /govuk/content-publisher/node_modules
```

Is there a prerequisite step I'm missing?

**Comment by kevindew** [comment]
> I had a quick try of this in Content Publisher (after `yarn install`) and got the following error.
> 
> ```
> Showing /home/build/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/bundler/gems/govuk_publishing_components-4a3828a5bb8b/app/views/govuk_publishing_components/components/_layout_for_admin.html.erb where line #11 raised:
> 
> couldn't find file 'axe-core/axe.js' with type 'application/javascript'
> Checked in these paths: 
>   /govuk/content-publisher/app/assets/config
>   /govuk/content-publisher/app/assets/images
>   /govuk/content-publisher/app/assets/javascripts
>   /govuk/content-publisher/app/assets/stylesheets
>   /home/build/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/bundler/gems/govuk_publishing_components-4a3828a5bb8b/app/assets/config
>   /home/build/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/bundler/gems/govuk_publishing_components-4a3828a5bb8b/app/assets/images
>   /home/build/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/bundler/gems/govuk_publishing_components-4a3828a5bb8b/app/assets/javascripts
>   /home/build/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/bundler/gems/govuk_publishing_components-4a3828a5bb8b/app/assets/stylesheets
>   /home/build/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/activestorage-6.0.2.2/app/assets/javascripts
>   /home/build/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/actionview-6.0.2.2/lib/assets/compiled
>   /home/build/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/bundler/gems/govuk_publishing_components-4a3828a5bb8b/node_modules/govuk-frontend/govuk/assets/images
>   /home/build/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/bundler/gems/govuk_publishing_components-4a3828a5bb8b/node_modules/govuk-frontend/govuk/assets/fonts
>   /home/build/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/bundler/gems/govuk_publishing_components-4a3828a5bb8b/node_modules/govuk-frontend
>   /home/build/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/bundler/gems/govuk_publishing_components-4a3828a5bb8b/node_modules
>   /govuk/content-publisher/node_modules
> ```
> 
> Is there a prerequisite step I'm missing?

Sure, I'm guessing you specified the github branch of this gem? This unfortunately doesn't work govuk_publishing_components as the gem needs to be packaged with node_modules. The way to try this out is to clone it locally run `npm install` and specify the gem via path.

This change won't change Content Publisher to use libsass though (even for viewing component-guide) - this only affects the spec/dummy app here so you'll only experience this when working on this gem directly rather than through an app.

**Comment by benthorner** [comment]
Aaah, I vaguely remember this caveat. Thanks for explaining!

**Comment by kevindew** [comment]
Ok - here goes! 🤞

**Pull request merged**
