### PR TITLE
Remove Universal Analytics

### PR DESCRIPTION
**Pull request by andysellick**
## What
Remove the Universal Analytics code. Supersedes https://github.com/alphagov/govuk_publishing_components/pull/4067

BREAKING CHANGES:

- details component no longer has a JS file
- TrackSelectChange (`track-select-change`) module has been removed, referenced in `finder-frontend` at least
- organisation logo no longer accepts data attributes passed to it
- intervention component no longer accepts data attributes passed to it
- image card component no longer accepts data attributes for child links

Things to potentially investigate further:

- does step nav (and related components) need the `tracking_id` option anymore? Looks like that value is recorded in the GA4 page view and nowhere else. ANSWER: yes it is needed, it gets used in session storage to record which bits of a step nav are open, have emphasised this in the comments for clarity.

## Why
Universal Analytics is being switched off at the end of June and has been replaced with Google Analytics 4.

## Visual Changes
Several visual changes, but all because of removed entries from YML files. This reflects that some components no longer have specific options for UA tracking, and some have had their ability to accept data attributes in some circumstances removed because this was only used for UA tracking.

Trello card: https://trello.com/c/rNPqwDIr/188-remove-ua-code-from-components-gem

### CODE REVIEW

**Comment by andysellick** [comment]
@AshGDS I think this is ready for review now but I'm going to leave it in draft for now because we're not ready to merge it, and might not be for a while. It's pretty big so no huge rush on reviewing it, happy to talk through it if you want 👍

**Review by AshGDS — COMMENTED** [review]
Nice work 👍  Got a few questions:

1. Do we need `data-youtube-player-analytics` references?
2. Do we need to keep the `domain-config` variables like `UA-UNSET`?
3. A reference to UA was left in a code comment - `app/views/govuk_publishing_components/components/_accordion.html.erb` line 51.
4. Does `cookie-functions.js` need some cleanup, e.g. removing `analytics_next_page_call`, `_gid`, and `_gat`? 
5. Does `with_track_show_all_clicks`, `with_track_sections`, need to remain in `accordion.yml`?
6. Does `with_unique_tracking` need to remain in `step_by_step_nav_header.yml`? Specifically the dimension96 mention. There's also a reference to `with_unique_tracking` in step_by_step_nav_related.yml as well.
7. `app/views/govuk_publishing_components/components/_contents_list.html.erb` line 53 has track data
8. If you search for `dimension` and `track_` in the code there are quite a few UA references to remove still. Maybe the ones in `.yml` files should just be renamed to be non tracking specific

**Comment by andysellick** [comment]
> Nice work 👍 Got a few questions:
> 
> 1. Do we need `data-youtube-player-analytics` references?
> 2. Do we need to keep the `domain-config` variables like `UA-UNSET`?
> 3. A reference to UA was left in a code comment - `app/views/govuk_publishing_components/components/_accordion.html.erb` line 51.
> 4. Does `cookie-functions.js` need some cleanup, e.g. removing `analytics_next_page_call`, `_gid`, and `_gat`?
> 5. Does `with_track_show_all_clicks`, `with_track_sections`, need to remain in `accordion.yml`?
> 6. Does `with_unique_tracking` need to remain in `step_by_step_nav_header.yml`? Specifically the dimension96 mention. There's also a reference to `with_unique_tracking` in step_by_step_nav_related.yml as well.
> 7. `app/views/govuk_publishing_components/components/_contents_list.html.erb` line 53 has track data
> 8. If you search for `dimension` and `track_` in the code there are quite a few UA references to remove still. Maybe the ones in `.yml` files should just be renamed to be non tracking specific

Thanks @AshGDS. I _think_ I've got all of these now. Apologies I've just realised that I've squashed the changes into pre-existing commits, so this is going to be harder for you to review.

**Review by AshGDS — APPROVED** [review]
Nice work, looks like it was a massive task 👍 🎉👏

**Comment by AshGDS** [comment]
@andysellick I've approved the visual changes as well 👍

**Pull request merged**
