### PR TITLE
Bump gem version to 17.18.1

### PR DESCRIPTION
**Pull request by DilwoarH**
Includes:

* Remove expectation that sprockets is installed when used in a Rails app (PR #999)
* Changes content item to have symbolic keys (PR #1002)
* Fix tabs list overwrite on mobile (PR #1003)
* Set the origin when rendering the YouTube player (PR #1004)

### CODE REVIEW

**Comment by vanitabarrett** [comment]
Does this need a line in the Changelog?

**Comment by DilwoarH** [comment]
> Does this need a line in the Changelog?

I decided against it as this is a bug fix and does not provide any usefulness in change notes.

**Comment by alex-ju** [comment]
@DilwoarH rebase this and pushed. Hope you don't mind. If you're happy with it please merge.

**Comment by alex-ju** [comment]
Closed in favour of #1006

**Pull request closed without merging**
