### PR TITLE
Remove vendored axe-core with latest axe-core via npm

### PR DESCRIPTION
**Pull request by nickcolley**
We have been building some pages that are in GOV.UK.

The bank holidays page throws errors for contrast so we updated the sizing of the text in our version.

I thought there might be an older version of axe-core which was not throwing this up in the component guide.

Turned out the error is only shown in Google Lighthouse (which uses axe-core) but not the official axe-core chrome extension.

So... here's a free upgrade :)

Updates axe-core v3.0.0-alpha.1 to v3.1.2

You do not have a documented (that I can see) which Node.js version you use, so I have updated the package-lock.json based on my current version: v8.9.4

### CODE REVIEW

**Comment by andysellick** [comment]
Thanks @nickcolley - very happy with this but there's some errors in the build, can you take a look?

**Comment by nickcolley** [comment]
@andysellick I tried running the tests and it said that every test was broken, can you look at the Jenkins output and see if there's anything obvious? Sorry for the hassle.

**Comment by andysellick** [comment]
The console output is saying...

```
1) Component examples with accessibility criteria shows the accessibility acceptance criteria as HTML
     Failure/Error: visit '/component-guide/test-component'

     Capybara::Poltergeist::JavascriptError:
       One or more errors were raised in the Javascript code on the page. If you don't care about these errors, you can ignore them by setting js_errors: false in your Poltergeist configuration (see documentation for details).

       TypeError: 'undefined' is not a function (evaluating 'window.btoa.bind(window)')
       TypeError: 'undefined' is not a function (evaluating 'window.btoa.bind(window)')
           at http://127.0.0.1:41658/assets/component_guide/application.js:1313
           at http://127.0.0.1:41658/assets/component_guide/application.js:986 in __webpack_require__
           at http://127.0.0.1:41658/assets/component_guide/application.js:1240 in getDefaultAdapter
           at http://127.0.0.1:41658/assets/component_guide/application.js:1247
           at http://127.0.0.1:41658/assets/component_guide/application.js:986 in __webpack_require__
           at http://127.0.0.1:41658/assets/component_guide/application.js:1173
           at http://127.0.0.1:41658/assets/component_guide/application.js:986 in __webpack_require__
           at http://127.0.0.1:41658/assets/component_guide/application.js:1000
           at http://127.0.0.1:41658/assets/component_guide/application.js:986 in __webpack_require__
           at http://127.0.0.1:41658/assets/component_guide/application.js:995
           at http://127.0.0.1:41658/assets/component_guide/application.js:986 in __webpack_require__
           at http://127.0.0.1:41658/assets/component_guide/application.js:993
           at http://127.0.0.1:41658/assets/component_guide/application.js:1755
           at http://127.0.0.1:41658/assets/component_guide/application.js:1756 in axeFunction
           at http://127.0.0.1:41658/assets/component_guide/application.js:13649
     # /var/lib/jenkins/bundles/ruby/2.4.0/gems/poltergeist-1.16.0/lib/capybara/poltergeist/browser.rb:377:in `command'
     # /var/lib/jenkins/bundles/ruby/2.4.0/gems/poltergeist-1.16.0/lib/capybara/poltergeist/browser.rb:36:in `visit'
     # /var/lib/jenkins/bundles/ruby/2.4.0/gems/poltergeist-1.16.0/lib/capybara/poltergeist/driver.rb:97:in `visit'
     # /var/lib/jenkins/bundles/ruby/2.4.0/gems/capybara-2.14.4/lib/capybara/session.rb:269:in `visit'
     # /var/lib/jenkins/bundles/ruby/2.4.0/gems/capybara-2.14.4/lib/capybara/dsl.rb:50:in `block (2 levels) in <module:DSL>'
     # ./spec/component_guide/component_example_accessibility_criteria_spec.rb:5:in `block (2 levels) in <top (required)>'
```

**Comment by andysellick** [comment]
@nickcolley any progress on this?

**Comment by nickcolley** [comment]
I believe it's an issue with axe relying on features that are not available in the runtime poltergiest uses (phantomjs, older webkit).

Will close, if anyone wants to pick this up feel free, sorry for the noise.

**Comment by alex-ju** [comment]
@nickcolley I'll try to carry on with the work, so please don't delete the branch yet. thanks again for raising this!

**Pull request closed without merging**
