### PR TITLE
Document how to move components upstream

### PR DESCRIPTION
**Pull request by nickcolley**
Rendered: https://github.com/alphagov/govuk_publishing_components/blob/c644f6c0878522941e2a47154178899d8cefb1f0/docs/moving-components-upstream-into-this-gem.md

### CODE REVIEW

**Comment by fofr** [comment]
This probably needs some work following #136

**Comment by nickcolley** [comment]
Someone else mind picking this up for me? 🙏

**Comment by fofr** [comment]
@nickcolley Updated

**Comment by nickcolley** [comment]
Much better thanks Paul 👍

**Pull request merged**
