### PR TITLE
Add panel component

### PR DESCRIPTION
**Pull request by alex-ju**
This PR adds panel component based on GOV.UK Frontend

[Trello card](https://trello.com/c/1fOAUyRc)

---

Component guide for this PR:
https://govuk-publishing-compon-pr-507.herokuapp.com/component-guide/panel

### CODE REVIEW

**Comment by tijmenb** [comment]
Is there reason to make it admin-layout only? It would be good to use this component in email-alert-frontend, I'm worried we'll forget about that otherwise.

**Comment by alex-ju** [comment]
It's dependent on `govuk-frontend` styles, that's why I added the admin layout to flag it as "needs govuk-frontend".

I would consider adding `govuk-frontend` to `email-alert-frontend` and import the needed css bit rather then duplicating the code from `govuk-frontend` to `govuk_publishing_components`

**Comment by tijmenb** [comment]
Can we only add the CSS for the panel component, like we do for https://github.com/alphagov/govuk_publishing_components/blob/master/app/assets/stylesheets/govuk_publishing_components/components/_button.scss#L14?

**Comment by alex-ju** [comment]
Yes, we can. We do this for a couple of components that are needed in projects that don't have govuk-frontend yet. I will do it this way then, but long term they would probably consume it directly.

**Pull request merged**
