### PR TITLE
Pass through label params for input

### PR DESCRIPTION
**Pull request by benthorner**
https://trello.com/c/l8MAts3s/205-build-the-index-page-with-filtering

This changes the input component so that any params for the label are passed through directly.

### CODE REVIEW

**Comment by benthorner** [comment]
@maxgds good point. I was going from this PR: https://github.com/alphagov/govuk_publishing_components/pull/508.

**Comment by tijmenb** [comment]
I think as long as there's a test that confirms the current behaviour (which I hope there is), it's fine to not add any for these. Needs an updated PR description though.

**Comment by benthorner** [comment]
@tijmenb I've checked the tests and they cover the previous (text) behaviour.

**Comment by benthorner** [comment]
@maxgds are you happy for us to continue?

**Comment by maxgds** [comment]
Sure, go for it.

**Pull request merged**
