### PR TITLE
Update jasmine gem

### PR DESCRIPTION
**Pull request by alex-ju**
## What
Update Jasmine gem from 2.4 to 3.4 (major) and precompile missing assets
Bring other dependencies to date (minors)

## Why
To keep project's dependencies up to date and be able to dockerize govuk_publishing_components

## Visual Changes
No visual changes.

## Note
A few tests are failing, will try and fix them now.

## Update
After a bunch of hours spent to understand our tests I've found the main causes of the flaky tests, so briefly the updates are:
- clear `sessionStorage` after each test dee29ef3000d7093b5a5ab6c5323e52d33014b63, otherwise step-by-step tests interfere
- reset `cookies` after each test  2450e9a otherwise cookie functions tests interfere with the cookie banner tests
- clone `DEFAULT_COOKIE_CONSENT` otherwise we operate on the same object affecting its default values 9d3bda3a4f8496ad1f56a5d156bc4dea611c1971 which results in interferences

Since it took me that long, I ended up linting the test files as I was looking at a lot of red-flagged code.

[Trello card](https://trello.com/c/hwMoAOau)

### CODE REVIEW

**Comment by alex-ju** [comment]
Thanks @vanitabarrett. I'm going to merge this as I'm confident in changes and want to avoid doing a lot of rebase work. Hope this will unblock govuk_publishing_components from being dockerized @benthorner.

**Comment by benthorner** [comment]
Almost @alex-ju ! Just one more thing: https://github.com/alphagov/govuk_publishing_components/pull/973.

**Comment by benthorner** [comment]
@alex-ju having done all the hard work on this, would you like to update https://github.com/alphagov/govuk-docker#compatibility?

**Comment by benthorner** [comment]
(I can confirm it now works.)

**Pull request merged**
