### PR TITLE
Remove deprecated components

### PR DESCRIPTION
**Pull request by alex-ju**
## What
Remove deprecated components: `admin_analytics`, `government_navigation`, `highlight_boxes` and `taxonomy_list`

## Why
Because they are not needed and we want to keep our codebase to a minimum to ease maintenance.

## Visual Changes
No visual changes (aside from the components being removed)

### CODE REVIEW

**Review by andysellick — APPROVED** [review]
Screenshot 2021-12-15 at 11 28 19

🚀

**Comment by owenatgov** [comment]
We now have a release for this impending in the form of https://github.com/alphagov/govuk_publishing_components/pull/2549. Could we rebase and merge this?

**Comment by alex-ju** [comment]
Thanks for looking out for this, Owen. Unfortunately, I'm not able to rebase this so either someone else is going to do it, or it will have to wait for another major release.

**Comment by owenatgov** [comment]
Rebased, just waiting for test to pass. Due to outside pressures this might not go into 28, in which case I'll update the milestone.

**Comment by alex-ju** [comment]
> Rebased, just waiting for test to pass. Due to outside pressures this might not go into 28, in which case I'll update the milestone.

Thanks a lot, Owen! It looks like a flakey test may need a re-run – really appreciate your help with this.

**Pull request merged**
