### PR TITLE
Change step by step navigation active step link state

### PR DESCRIPTION
**Pull request by andysellick**
Adds underline to the currently active step link, following user research.

Before:

Screen Shot 2019-06-18 at 11 09 32

After:

Screen Shot 2019-06-18 at 11 09 41

Also changes the active link 'dot' to a line, to look like this:

Screen Shot 2019-06-18 at 14 50 20

### CODE REVIEW

**Comment by DilwoarH** [comment]
Should it be styled more like this instead:

Screen Shot 2019-06-18 at 11 59 06

**Comment by andysellick** [comment]
Not sure. Waiting on Kate.

**Comment by DilwoarH** [comment]
We should maybe remove the $dot-size variable to avoid confusion for new developers.

**Comment by andysellick** [comment]
> We should maybe remove the $dot-size variable to avoid confusion for new developers.

I already did.

**Pull request merged**
