### PR TITLE
Hide zero values

### PR DESCRIPTION
**Pull request by chris-gds**
## What?

Within `govspeak` `magna-charta` stacked charts, hiding zeros
+
updating docs with example.

## Why?

Zendesk ticket flagged an issue regarding overlapping zeros from Content teams when using Stacked charts
After [discussion (ticket)](https://trello.com/c/ghmrZy8g) solution was to hide zeros.
image

## Visual Changes
**Before:**
Screenshot 2020-11-11 at 08 33 57
**After:**
Screenshot 2020-11-11 at 08 34 10

---
The new element to appear [within the docs](https://components.publishing.service.gov.uk/component-guide/govspeak)
Screenshot 2020-11-12 at 17 42 50

## Anything else

[Example page where this type of chart is used](https://www.gov.uk/government/publications/coronavirus-job-retention-scheme-statistics-october-2020/coronavirus-job-retention-scheme-statistics-october-2020#employments-furloughed-over-time-by-gender)

- Attention on this type of chart highlighted some other usability concerns (eg The "total" number isn't clear, this is a total?)
- Small numbers 1-5
- Conversations in general about visual data-use on govuk

### CODE REVIEW

**Review by injms — COMMENTED** [review]
Can you add the example to the documentation so that we don't forget about this type of chart? Otherwise we run the risk of forgetting about this particular use case.

**Comment by chris-gds** [comment]
> Can you add the example to the documentation so that we don't forget about this type of chart? Otherwise we run the risk of forgetting about this particular use case.

Figured that was a risk as well, [I've created card](https://trello.com/c/lwsS7kxS) for that one so it doesn't fall off the radar. I thought there might be some more a11y considerations or use-cases to mention on the docs so thought it made sense to fix first as it wasn't on the docs to start.  What do you think?

**Review by injms — APPROVED** [review]
Thanks for adding the documentation for the stacked chart - I think it's good that the example highlights that the thinner bars have barely enough space for the numbers inside as it shows that its a problem.

Super 🚀 🚢

**Comment by chris-gds** [comment]
Resolved merge conflict via github - nifty :)

**Comment by chris-gds** [comment]
> Thanks for adding the documentation for the stacked chart - I think it's good that the example highlights that the thinner bars have barely enough space for the numbers inside as it shows that its a problem.
> 
> Super 🚀 🚢

Agreed, the smaller numbers show this issue well (props to Owen too, he initially recreated the docs code when he touched this)

**Comment by alex-ju** [comment]
For future work, I suggest using `git rebase` as the GitHub interface way leaves merge commits, such as _Merge branch 'master' into fix-stacked-barchart_ that add clutter to our git history.

**Comment by chris-gds** [comment]
> For future work, I suggest using `git rebase` as the GitHub interface way leaves merge commits, such as _Merge branch 'master' into fix-stacked-barchart_ that add clutter to our git history.

Fair, saw this shiny resolve button on direct GitHub and thought I'd give this a click 🙈.  I see how this is preferred.

**Pull request merged**
