### PR TITLE
Bump gem version to 23.12.3

### PR DESCRIPTION
**Pull request by owenatgov**
Includes:
* Fix text overflow bug in Firefox ([PR #1764](https://github.com/alphagov/govuk_publishing_components/pull/1764))
* Tidy component filenames ([PR #1848](https://github.com/alphagov/govuk_publishing_components/pull/1848))
* Add print styling for magna charta component ([PR #1867](https://github.com/alphagov/govuk_publishing_components/pull/1867))
* Add custom aria label option for layout header nav ([PR #1865](https://github.com/alphagov/govuk_publishing_components/pull/1865))
* Change GOVUK Modules scope to document ([PR #1869](https://github.com/alphagov/govuk_publishing_components/pull/1869))

### CODE REVIEW

**Comment by injms** [comment]
Can we hold onto this release for the time being? There looks to be a couple of other things that could be added to this in the next couple of days, and that would help avoid numerous releases and having to update all the apps again and again.

**Comment by andysellick** [comment]
Yes, I'd really like to get https://github.com/alphagov/govuk_publishing_components/pull/1848 and https://github.com/alphagov/govuk_publishing_components/pull/1764 in if possible - anyone able to review?

**Comment by owenatgov** [comment]
I'm perfectly fine with this. Let me know when we can put it out. Presumably we'd review if a fix version would still be suitable? Should I close this now just in case?

**Comment by injms** [comment]
> I'm perfectly fine with this. Let me know when we can put it out. Presumably we'd review if a fix version would still be suitable? Should I close this now just in case?

Let's keep it open for now with a do not merge label - then if it needs closing later we can do that then?

**Comment by andysellick** [comment]
I've merged https://github.com/alphagov/govuk_publishing_components/pull/1848

**Comment by owenatgov** [comment]
@andysellick Did you want to wait until #1764 was merged?

**Comment by andysellick** [comment]
@owenatgov no that's fine, it's not urgent.

**Comment by danacotoran** [comment]
@owenatgov we've got [a few PR's](https://github.com/alphagov/govuk_publishing_components/blob/master/CHANGELOG.md#unreleased) in Unreleased now, do you want to rebase this and do the honours (unless are we waiting for another merge to happen first)?

**Comment by owenatgov** [comment]
Ready to roll, just needs an approve and we're good.

**Comment by DilwoarH** [comment]
Can we rebase and add this please https://github.com/alphagov/govuk_publishing_components/pull/1869?

**Comment by owenatgov** [comment]
@DilwoarH done

**Review by andysellick — APPROVED** [review]
Can we update the PR description to include all the changes in this version?

**Comment by DilwoarH** [comment]
> Can we update the PR description to include all the changes in this version?

Done

**Review by DilwoarH — APPROVED** [review]

**Pull request merged**
