### PR TITLE
Release 28.8.0

### PR DESCRIPTION
**Pull request by edwardkerry**
## What
Release version 28.8.0

### CODE REVIEW

**Review by chris-gds — APPROVED** [review]

**Comment by andysellick** [comment]
@edwardkerry can I get https://github.com/alphagov/govuk_publishing_components/pull/2646 into this release please? Shouldn't take long.

**Comment by andysellick** [comment]
https://github.com/alphagov/govuk_publishing_components/pull/2646 is approved (thanks @alex-ju!) just waiting on the tests to pass before I can merge.

**Comment by edwardkerry** [comment]
Thanks @andysellick, any chance of a review?

**Review by andysellick — APPROVED** [review]
🚀

**Pull request merged**
