### PR TITLE
Add missing class for slimmer header

### PR DESCRIPTION
**Pull request by chao-xian**
## What

This class is required for slimmer to inject service titles. For example the Service Manual.

## Why

The old template had this class, [and Slimmer expects it in order to inject a custom title header](https://github.com/alphagov/slimmer/blob/master/lib/slimmer/processors/inside_header_inserter.rb#L7-L8).

[Trello card](https://trello.com/c/7xbAX1Uk/711-bug-fix-service-manual-header)

## Visual Changes

None

## Related PRs

* https://github.com/alphagov/static/pull/2672
* https://github.com/alphagov/service-manual-frontend/pull/1021

### CODE REVIEW

**Review by owenatgov — COMMENTED** [review]
Changelog pls then I'll approve 🙏

**Review by owenatgov — APPROVED** [review]
🎅

**Review by alex-ju — COMMENTED** [review]
Alternatively, we could've updated `slimmer to use the existing `gem-c-header__logotype`. I am slightly worried that someone will find this class without any associated styles and will just get rid of it.

**Comment by chao-xian** [comment]
Ah good point @alex-ju - which might be how it happened in the first place. I'll raise a couple PRs if I get a chance.

**Pull request merged**
